import type { Metadata } from 'next';
import StyledComponentsRegistry from '@/lib/AntdRegistry';

/* Components */
import { Providers } from '@/lib/Providers';

/* Instruments */
import '@/styles/globals.scss';

export const metadata: Metadata = {
  title: 'Website by Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: React.PropsWithChildren) {
  return (
    <Providers>
      {/* 使用 App Router 需要加这行， antd 首屏样式按需抽离并植入到 HTML 中，以避免页面闪动的情况 */}
      <StyledComponentsRegistry>
        <html lang='en'>
          <body>{props.children}</body>
        </html>
      </StyledComponentsRegistry>
    </Providers>
  );
}
