import './styles/globals.scss';
import type { Metadata } from 'next';
import StyledComponentsRegistry from '@/lib/AntdRegistry';

/* Components */
import { Providers } from '@/lib/Providers';
import { Nav } from './components/Nav';

/* Instruments */
import styles from './styles/layout.module.scss';
import './styles/globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: React.PropsWithChildren) {
  return (
    <Providers>
      {/* 使用 App Router 需要加这行， antd 首屏样式按需抽离并植入到 HTML 中，以避免页面闪动的情况 */}
      <StyledComponentsRegistry>
        <html lang='en'>
          <body>
            <section className={styles.container}>
              <Nav />

              <header className={styles.header}>
                <img src='/next.svg' className={styles.logo} alt='logo' />
              </header>

              <main className={styles.main}>{props.children}</main>

              <footer className={styles.footer}>
                <span>Learning never stop</span>
              </footer>
            </section>
          </body>
        </html>
      </StyledComponentsRegistry>
    </Providers>
  );
}
